name: Merge Schedule
on:
  pull_request:
    types:
      - synchronize
  schedule:

    - cron: 30 13 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}